spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/voting_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Himani@123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
spring.jpa.open-in-view=false

server.port=${PORT:8080}